---
- name : lamp stack
  hosts : localhost
  become : true
  tasks :
   # install apache
   - name : install httpd
     ansible.builtin.dnf:
       name : httpd
       state: present
   - name : start and enable httpd
     ansible.builtin.service:
      name : httpd
      state : started
      enabled : true
   # install mariadb
   - name : install mariadb
     ansible.builtin.dnf:
      name : mariadb105-server
      state: present
   - name :   start and enable mariadb
     ansible.builtin.systemd_service:
       name : mariadb
       state : started
       enabled : true

   # install php
   - name : install php
     ansible.builtin.dnf:
      name : php
      state: present


   # install php-fpm
   - name : install php-fpm
     ansible.builtin.dnf:
       name : php-fpm
       state : present
   - name : start and enable php-fpm
     ansible.builtin.systemd_service:
      name : php-fpm
      state : started
      enabled : true

  # deploy php page
   - name : deploy php file
     ansible.builtin.copy:
      dest : /var/www/html/index.php
      content : |
        <?php
         echo "<h1>LAMP Stack Deployed using Ansible</h1>";
        ?>
